<?php
/*********************************
List Images page displays all the current 
images from the database WITHOUT any
text

After the user selects an image
then the page should send the user
to the create-meme.php page

image_id is to be sent through 
$_GET or $_SESSION
*********************************/
include( "includes/db.inc.php");

session_start();


?><!doctype html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Meme List - Meme Generator</title>
	<?php
	include_once( "includes/scripts.inc.php");
	?>
</head>

<body>
	<div class="wrapper imagesPage">
		<header class="masthead">
			<?php
			include_once("includes/masthead.inc.php");
			?>
		</header>
		
		<nav class="nav" role="navigation">
			<?php
			include_once("includes/nav.inc.php");
			?>	
		</nav>
		
		<section class="main imagesIn menuActive">
			<h2>Choose an Image to Make a Meme</h2>
			<?php
			//the list below to be generated by PHP
			//by selecting the list of images from the database
			?>
			<ul id="addImages" class="memes">
			<?php
			 $query= $link->query('SELECT * FROM mtm4057_meme_images');

    if($query)
    {

//loop through assoc array
      while($row =$query->fetch(PDO::FETCH_ASSOC)) {

//put the values of each $row array in $data_array
//this is to echo out proper json
//if this is not done and just $row is echoed out the it will be like {} , which is syntax error for json

     
      echo'<li>
		<a href="add-text.php?i='.$row["image_id"].'"><img src="images-memes/resized_'.$row["file_name"].'.jpg"><span class="imageTitle">'.$row["image_title"].'</span><span class="centerText">Add Text to this image</span></a>
				</li>
      ';
    }
}
       ?> 
          
         
			</ul>
				
		</section>
		
		<footer class="footer">
			<?php
			include_once("includes/footer.inc.php");
			?>
		</footer>
	</div>
	<script  type="text/javascript" src="js/custom.js"></script>
</body>
</html>